// this comtains the data we are gonna for AboutMe component and slider component 

export const AboutData = [
  {
    count: 1,
    title: "Programming Languages",
    img: "/first.svg",
    array: [
      "Python",
      "Java",
      "JavaScript",
      "PHP",
      "SQL",
    ],
  },
  {
    count: 2,
    title: "Front-end Development",
    img: "/second.svg",
    array: [
      "HTML / CSS",
      "React.js",
      "Next.js",
      "Redux",
      "Tailwind CSS",
      "Responsive UI",
    ],
  },
  {
    count: 3,
    title: "Back-end & API Development",
    img: "/third.svg",
    array: [
      "Node.js / Express.js",
      "Laravel",
      "Symfony",
      "Spring Boot",
      "Flask",
      "FastAPI",
      "REST APIs",
      "GraphQL",
      "gRPC",
    ],
  },
  {
    count: 4,
    title: "Databases & Data Engineering",
    img: "/fourth.svg",
    array: [
      "MySQL",
      "MongoDB",
      "SQLite",
      "RxDB",
      "Data Warehousing",
      "ETL Pipelines",
      "SQLAlchemy",
      "Power Query",
      "Power BI",
    ],
  },
  {
    count: 5,
    title: "AI, ML & Deep Learning",
    img: "/fifth.svg",
    array: [
      "Pandas",
      "NumPy",
      "Data Analysis",
      "Data Visualization",
      "Scikit-learn",
      "TensorFlow",
      "Keras",
      "Computer Vision",
      "Model Evaluation",
    ],
  },
  {
    count: 6,
    title: "MLOps & Automation",
    img: "/sisxth.svg",
    array: [
      "Docker",
      "Airflow",
      "DVC",
      "MLflow",
      "Jupyter / nbconvert",
      "Model Registry",
      "Reproducibility",
    ],
  },
  {
    count: 7,
    title: "Mobile & Desktop Development",
    img: "/fourth.svg",
    array: [
      "Android Studio",
      "Java Swing",
      "Firebase",
      "Cloudinary",
      "JDBC",
    ],
  },
  {
    count: 8,
    title: "Tools, Messaging & Delivery",
    img: "/third.svg",
    array: [
      "Git / GitHub",
      "UML",
      "XAMPP / Laragon",
      "Postman",
      "Agile / Scrum",
      "Apache Kafka",
      "Apache Kafka Streams",
      "Apache Airflow",
    ],
  },
];


// this is for the slider 
export const DataArray = [
  {
    title: "Smart School Attendance and Analytics System",
    name: "Alexander Academy Attendance System",
    des: "A comprehensive school attendance and analytics system developed for Alexander Academy in Canada. This project was fully completed during a 3-month summer internship, featuring dashboards for real-time monitoring, authentication, role-based access control, and advanced data visualization capabilities.",
    des1: "This project was built using React.js, Redux, Flask, Python, and JavaScript. It includes real-time monitoring dashboards, secure authentication systems, role-based access control, and comprehensive data visualization features to help administrators track and analyze student attendance patterns.",
    technologies: ["React.js", "Redux", "Flask", "Python", "JavaScript"],
    images: ["/projects/registre1.jpeg", "/projects/registre2.jpeg", "/projects/registre3.jpeg","/projects/registre4.jpeg","/projects/registre5.jpeg","/projects/registre6.jpeg","/projects/registre7.jpeg"],
  },
  {
    title: "Hannibal Market - Multi-Vendor E-Commerce Platform",
    name: "Hannibal Market",
    des: "A full-featured multi-vendor e-commerce platform with integrated real-time messaging and comprehensive vendor management features. Developed following agile practices and delivered as a complete production-ready solution.",
    des1: "This platform was built using Laravel, JavaScript, jQuery, Blade templates, HTML, and CSS. It features real-time messaging capabilities, advanced vendor management tools, and a complete e-commerce solution ready for production deployment.",
    technologies: ["Laravel", "JavaScript", "jQuery", "Blade", "HTML", "CSS"],
    images: ["/projects/ecommerce1.png","/projects/ecommerce2.png","/projects/ecommerce3.png","/projects/ecommerce4.png","/projects/ecommerce5.png","/projects/ecommerce6.png","/projects/ecommerce7.png","/projects/ecommerce8.png","/projects/ecommerce9.png","/projects/ecommerce10.png","/projects/ecommerce11.png","/projects/ecommerce12.png","/projects/ecommerce13.png","/projects/ecommerce14.png","/projects/ecommerce15.png","/projects/ecommerce16.png","/projects/ecommerce17.png"],
  },
  {
    title: "Data Warehouse Project – Power BI vs Python",
    name: "Northwind Data Warehouse",
    des: "Designed and implemented a dual-implementation Data Warehouse using the Northwind database. Built comprehensive ETL pipelines and analytical dashboards using both Python with SQLAlchemy and Power BI with Power Query.",
    des1: "This project demonstrates expertise in data engineering with dual implementations using Python (SQLAlchemy) and Power BI (Power Query). It includes complete ETL pipelines, data transformation processes, and interactive analytical dashboards for business intelligence. You can find the github repo of this project in this link: https://github.com/SafwenCherif/Data-Warehouse-BI-Project",
    technologies: ["Python", "SQLAlchemy", "Power BI", "Power Query", "ETL", "SQL"],
    images: ["/projects/BI100.png","/projects/dw1.png", "/projects/dw2.png", "/projects/dw3.png", "/projects/dw4.png","/projects/dw5.png","/projects/dw6.png","/projects/dw7.png"],
      repo: "https://github.com/SafwenCherif/Data-Warehouse-BI-Project",
  },
  {
    title: "Mobile E-Commerce Application with Delivery System",
    name: "Echrini.tn :E-Commerce Mobile App",
    des: "Developed a comprehensive Android e-commerce application featuring order tracking, a complete delivery system, and in-app messaging capabilities. Built with modern mobile development practices and cloud integration.",
    des1: "This Android application was developed as a light-weight academic project using Android Studio, Java, Firebase, and Cloudinary. It includes full e-commerce functionality, real-time order tracking, delivery management system, and integrated messaging features for seamless customer communication.",
    technologies: ["Android Studio", "Java", "Firebase", "Cloudinary"],
    images: [
      "/projects/echrini1.png",
      "/projects/echrini2.png",
      "/projects/echrini3.png",
      "/projects/echrini4.png",
      "/projects/echrini5.png",
      "/projects/echrini6.png",
      "/projects/echrini7.png",
      "/projects/echrini8.png",
      "/projects/echrini9.png",
      "/projects/echrini10.png",
      "/projects/echrini11.png",
      "/projects/echrini12.png",
      "/projects/echrini13.png",
      "/projects/echrini14.png",
      "/projects/echrini15.png",
      "/projects/echrini16.png",
      "/projects/echrini17.png",
      "/projects/echrini18.png",
      "/projects/echrini19.png",
      "/projects/echrini20.png",
    ],
  },
  {
  title: "Hotel Management System",
  name: "Hotel Management System (Java Swing)",
  des: "A comprehensive desktop application for managing hotel operations including room reservations, employee management, and customer check-in/checkout processes.",
  des1: "This desktop application provides complete hotel management functionality for administrators to manage rooms, employees, and customer reservations. Features include real-time room availability tracking, automated billing, customer check-in/checkout systems, and employee scheduling. The system uses Java Swing for an intuitive desktop interface and JDBC for seamless database connectivity with MySQL.",
  technologies: ["Java", "Java Swing", "JDBC", "MySQL", "XAMPP"],
  images: ["/projects/hotel1.png", "/projects/hotel2.png", "/projects/hotel3.png","/projects/hotel4.png","/projects/hotel5.png","/projects/hotel6.png","/projects/hotel7.png","/projects/hotel8.png","/projects/hotel9.png","/projects/hotel10.png"],
},
{
  title: "Health Management System",
  name: "Web-Based Health Management System",
  des: "A comprehensive web-based healthcare management platform for managing medical professionals, patient records, appointments, and administrative operations.",
  des1: "This full-featured web application provides complete healthcare management functionality including doctor profiles management, patient electronic health records (EHR), appointment scheduling system, prescription management, billing and invoicing, and role-based access control for administrators, doctors, and patients. Built with Django framework for robust backend functionality and secure data handling.  You can find the github repo of this project in this link: https://github.com/SafwenCherif/hospital-system",
  technologies: ["HTML", "CSS", "Django", "SQLite", "Python", "Bootstrap"],
  images: ["/projects/h1.png", "/projects/h2.png", "/projects/h3.png", "/projects/h4.png", "/projects/h5.png", "/projects/h6.png", "/projects/h7.png", "/projects/h8.png", "/projects/h9.png", "/projects/h10.png", "/projects/h11.png", "/projects/h12.png", "/projects/h13.png", "/projects/h14.png", "/projects/h15.png"],
  repo: "https://github.com/SafwenCherif/hospital-system",
},
{
  title: "EduCore - E-Learning Platform",
  name: "EduCore",
  des: "A comprehensive Udemy-like e-learning platform where users can enroll in courses, instructors can create content, and administrators manage the entire educational ecosystem.",
  des1: "EduCore is a full-featured e-learning platform that mimics popular online course marketplaces. The system includes role-based access for students, instructors, and administrators. Instructors can create, manage, and publish courses with multimedia content, while students can browse, enroll, and track their learning progress. Features include video lectures, quizzes, assignments, progress tracking, certification, and a secure payment system for course purchases.",
  technologies: ["Laravel", "PHP", "JavaScript", "jQuery", "MySQL", "Laragon", "HTML", "CSS", "Bootstrap", "Blade"],
  images: ["/projects/learning1.png", "/projects/learning2.png", "/projects/learning3.png", "/projects/learning4.png", "/projects/learning5.png", "/projects/learning6.png", "/projects/learning7.png", "/projects/learning8.png", "/projects/learning9.png", "/projects/learning10.png", "/projects/learning11.png", "/projects/learning12.png", "/projects/learning13.png", "/projects/learning14.png"],
},
  {
  title: "MyBloggy - Blogging Platform",
  name: "MyBloggy",
  des: "A full-featured blogging platform where users can create accounts, publish posts, and follow each other. Built with modern web technologies for an engaging social blogging experience.",
  des1: "This blogging platform includes user authentication, post creation and management, social features like following other users, and a complete content management system. Developed using React.js, Node.js, Express.js, and MongoDB for a scalable and modern blogging experience. You can find the github repo of this project in this link: https://github.com/SafwenCherif/MyBloggy-Blogging-Platform",
  technologies: ["React.js", "Node.js", "Express.js", "MongoDB", "JavaScript", "CSS", "HTML", "REST API"],
  images: ["/projects/blog1.png", "/projects/blog2.png", "/projects/blog3.png", "/projects/blog4.png", "/projects/blog5.png", "/projects/blog6.png", "/projects/blog7.png", "/projects/blog8.png", "/projects/blog9.png"],
  repo: "https://github.com/SafwenCherif/MyBloggy-Blogging-Platform",
},
{
  title: "TripSummit - Travel Agency Platform",
  name: "TripSummit",
  des: "A comprehensive travel agency web platform for managing travel bookings, destinations, and customer interactions. Built with Laravel and modern web technologies.",
  des1: "This travel agency platform provides complete functionality for managing travel bookings, destinations, customer information, and travel packages. Developed using HTML, CSS, Blade templates, Laravel, MySQL, and Laragon for a professional travel management solution.",
  technologies: ["HTML", "CSS", "Blade", "Laravel", "MySQL", "Laragon", "PHP", "JavaScript", "Bootstrap"],
  images: ["/projects/travel1.png", "/projects/travel2.png", "/projects/travel3.png", "/projects/travel4.png", "/projects/travel5.png", "/projects/travel6.png", "/projects/travel7.png", "/projects/travel8.png", "/projects/travel9.png", "/projects/travel10.png"],
},
{
  title: "NeuroScanAI — Brain Tumor Detection & Segmentation",
  name: "NeuroScanAI",
  des: "End-to-end two-stage deep learning pipeline that screens MRI slices for brain tumors (ResNet50 classifier) and performs precise tumor localization (ResUNet) only when a tumour is suspected. Includes a production-ready FastAPI backend that loads models at startup and serves asynchronous `/predict` inference with base64 overlays.",
  des1: "Summary: The system uses a high-sensitivity ResNet50 classifier (threshold 0.25) to minimize missed tumours, then runs a ResUNet segmentor with a Focal Tversky loss to generate crisp tumour masks. The FastAPI service initializes and caches both models on startup, exposes an asynchronous `/predict` endpoint that accepts multipart uploads, normalizes inputs, runs the cascaded inference, and returns JSON containing probabilities, optional segmentation masks (as base64 overlays), and metadata. The backend is Dockerized for deployment and designed to work with a Next.js frontend that visualizes overlays, heatmaps and result metadata. Technologies: distributed GPU training, model export (Keras/SavedModel/TFLite), threshold calibration, and robust pipeline engineering to avoid leakage and double-augmentation bugs.",
  technologies: ["Python", "TensorFlow", "Keras", "ResNet50", "ResUNet", "Focal Tversky Loss", "FastAPI", "Docker", "Next.js", "TFLite"],
  repo: "https://github.com/SafwenCherif/Deep-Project",
  images: ["/projects/dl.png", "/projects/dl1.png", "/projects/dl2.png", "/projects/dl3.png", "/projects/dl4.png"],
},
{
  title: "Tunisian Real Estate MLOps — Apartment Price Prediction",
  name: "Tunisian Real Estate MLOps",
  des: "A fully automated MLOps pipeline that scrapes new Tunisian apartment listings, enriches them with geographic features, retrains a price-prediction model when the data changes, promotes the best model through MLflow, and backs up artifacts with DVC.",
  des1: "Summary: This production-grade system runs on a daily Airflow schedule, checks whether Mubawab has new listings, scrapes only new rows through content-based fingerprinting, geocodes and enriches them with location features, executes the EDA and modeling notebooks headlessly, and compares the latest run against the current champion in MLflow before promoting a new model only when it materially improves performance. The stack is fully containerized with Docker and built around Python, Airflow, DVC, MLflow, Scikit-learn, BeautifulSoup, Geopy, and Nominatim. The current champion is Ridge Regression, chosen for its strong R² and stable average error on Tunisian apartment prices, and the whole pipeline is designed for reproducibility, automated backups, and zero human intervention.",
  technologies: ["Python", "Airflow", "DVC", "MLflow", "Docker", "Scikit-learn", "BeautifulSoup", "Geopy", "Nominatim", "Jupyter"],
  repo: "https://github.com/SafwenCherif/tunisian-real-estate-mlops",
  images: ["/projects/mlops.png"],
},
{
  title: "Food Delivery — Microservices Architecture",
  name: "Food Delivery Microservices",
  des: "A fully functional food-delivery platform built with a Node.js microservices architecture, exposing REST and GraphQL through an API gateway and coordinating catalogue, order, and delivery services through gRPC and Apache Kafka.",
  des1: "Summary: The system cleanly separates the API gateway from three backend services and uses gRPC for service-to-service communication, REST for core endpoints, GraphQL for cross-service queries, and Kafka for event-driven updates. The catalogue service manages products in RxDB, the order service manages order lifecycle state in SQLite, and the delivery service assigns drivers and tracks delivery status in SQLite. The gateway exposes /products, /orders, /deliveries, and /graphql, while Kafka topics such as order.created, order.status.updated, and delivery.updated keep the services synchronized. The project demonstrates production-style Node.js service design, asynchronous event handling, and a unified developer workflow documented through Postman collections and Docker-ready setup instructions.",
  technologies: ["Node.js", "Express.js", "gRPC", "GraphQL", "Apache Kafka", "RxDB", "SQLite3", "Docker", "Postman", "REST API"],
  repo: "https://github.com/Project-SOA/SOA-Project",
  images: ["/projects/microservices.png"],
},
{
  title: "Hotel Reservation MLOps — Complete Project Reference",
  name: "Hotel Reservation MLOps",
  des: "Production-grade end-to-end MLOps pipeline: from raw data to a live public prediction API on Google Cloud Run with CI/CD automation through Jenkins, Docker, and Google Container Registry.",
  des1: "Full project including local training pipeline, Jenkins CI/CD (custom Jenkins image), Dockerfile, MLflow tracking (SQLite), and automated deploys to Cloud Run. Last updated: 2026-07-22. Live app: https://ml-project-254464063395.us-central1.run.app/",
  technologies: ["Python", "LightGBM", "MLflow", "Flask", "Jenkins", "Docker", "Google Cloud Run", "GCR", "GCS", "CI/CD"],
  images: ["/projects/hotel-mlops2.png", "/projects/hotel-mlops1.png"],
  repo: "https://github.com/SafwenCherif/hotel-reservation-mlops",
},
{
  title: "Medical RAG Chatbot — LLMOps Delivery Pipeline",
  name: "Medical RAG Chatbot",
  des: "A medical Retrieval-Augmented Generation chatbot grounded in The Gale Encyclopedia of Medicine, with a full LLMOps path: Docker packaging, Jenkins CI/CD, Trivy image scanning, and publishing to Amazon ECR.",
  des1: "Summary: Users ask medical questions in a Flask chat UI; the system optionally corrects medical-term typos, retrieves the top matching encyclopedia chunks from a local FAISS index (all-MiniLM-L6-v2 embeddings), and generates a short answer with Groq (OpenRouter fallback) under a context-constrained prompt. The offline path loads a PDF corpus, chunks it, embeds it, and persists FAISS; the online path serves grounded Q&A without re-indexing. Around the app sits an LLMOps delivery chain — setuptools packaging, CPU-only Docker builds, Jenkins pipelines, Trivy vulnerability scans, Amazon ECR publish, and optional AWS App Runner deploy. Built and validated on Ubuntu with Python 3.12.",
  technologies: ["Python", "Flask", "LangChain", "FAISS", "Sentence-Transformers", "Groq", "OpenRouter", "Docker", "Jenkins", "Trivy", "AWS ECR", "CI/CD"],
  images: ["/projects/Medical-Rag-LLMops1.png", "/projects/Medical-Rag-LLMops2.png", "/projects/Medical-Rag-LLMops3.png"],
  repo: "https://github.com/SafwenCherif/Medical-Rag-Chatbot-LLMops",
},
{
  title: "YouTube Channel Analytics ELT Pipeline",
  name: "YouTube Analytics ELT",
  des: "A full ELT data engineering pipeline that extracts YouTube channel metadata via the Data API v3, lands dated JSON snapshots, loads them into a PostgreSQL warehouse (staging + core), and validates quality with Soda — all orchestrated by Airflow in Docker Compose with GitHub Actions CI/CD.",
  des1: "Summary: The pipeline extracts public video metadata and engagement stats for a YouTube channel (default MrBeast) using a nested Russian-doll API pattern (Channels → PlaylistItems → Videos), lands near-raw JSON under ./data/, then loads into PostgreSQL with a staging schema close to source and a core schema with cleaned types plus Video_Type (Shorts vs Normal). Apache Airflow 2.9.2 with CeleryExecutor chains three DAGs — produce_json → update_db → data_quality — with insert/update/delete reconciliation, Soda Core checks, pytest unit and integration tests, and a GitHub Actions workflow that builds a custom Airflow image and runs the Compose stack on push.",
  technologies: ["Python", "YouTube Data API", "Apache Airflow", "PostgreSQL", "Docker Compose", "Celery", "Redis", "Soda Core", "pytest", "GitHub Actions"],
  images: ["/projects/yt-data-engineering1.png", "/projects/yt-data-engineering2.png", "/projects/yt-data-engineering3.png"],
  repo: "https://github.com/SafwenCherif/ETL-Data-engineering-and-warehousing",
},
{
  title: "Anime Recommender — End-to-End MLOps",
  name: "Anime Recommendations MLOps",
  des: "A hybrid anime recommendation system combining collaborative and content-based filtering, trained with TensorFlow embeddings and deployed as a Flask service on GKE through a fully automated Jenkins CI/CD pipeline on GCP.",
  des1: "Summary: Users enter a user_id and receive top-10 anime recommendations from a neural collaborative filtering model (TensorFlow/Keras embeddings with cosine-similarity scoring) blended with content-similar titles via weighted hybrid scoring. The MLOps path covers GCS data storage with DVC versioning, a three-stage training pipeline (ingest → process → train), Comet ML experiment tracking, Docker packaging, a custom Jenkins-with-GCP image, GCR image publishing, and GKE Deployment + LoadBalancer serving. Built with Python 3.12 on Google Cloud (GCS, GCR, GKE).",
  technologies: ["Python", "TensorFlow", "Flask", "GCS", "DVC", "Comet ML", "Docker", "Jenkins", "GCR", "GKE", "CI/CD"],
  images: ["/projects/anime-recommender-mlops1.png", "/projects/anime-recommender-mlops2.png"],
  repo: "https://github.com/SafwenCherif/anime-recommender-mlops",
},
{
  title: "Titanic Survival Prediction — Full MLOps Pipeline",
  name: "User Survival MLOps",
  des: "A production-style MLOps system for Titanic passenger survival prediction: GCP storage, Astro Airflow ETL into PostgreSQL, Redis feature store, Random Forest training, Flask serving with Alibi Detect drift monitoring, and Prometheus + Grafana observability.",
  des1: "Summary: Raw Titanic CSV lands in GCS, an Astro Airflow DAG loads it into PostgreSQL, then a Python pipeline ingests train/test splits, engineers features with SMOTE, stores passenger entities in Redis, and trains a Random Forest via RandomizedSearchCV by reading from the feature store. Predictions are served through Flask with Alibi Detect KSDrift on live inputs, while Prometheus scrapes custom counters (prediction_count_total, drift_count_total) visualized in Grafana. Built and documented on Ubuntu with Docker and Python 3.12.",
  technologies: ["Python", "Astro Airflow", "GCP GCS", "PostgreSQL", "Redis", "scikit-learn", "SMOTE", "Flask", "Alibi Detect", "Prometheus", "Grafana", "Docker"],
  images: ["/projects/User-survival-mlops1.png", "/projects/User-survival-mlops2.png"],
  repo: "https://github.com/SafwenCherif/User-survival-mlops",
},
{
  title: "Network Security MLOps — Phishing Website Detection",
  name: "Network Security MLOps",
  des: "An end-to-end MLOps pipeline for phishing website detection: MongoDB Atlas data store, modular training with schema/drift validation and GridSearchCV, MLflow tracking, Amazon S3 artifact storage, and FastAPI serving on AWS EC2 via Docker and GitHub Actions CI/CD.",
  des1: "Summary: Training data lives in MongoDB Atlas (PhishingRecords); a four-stage pipeline ingests to a feature-store CSV, validates schema and KS drift, applies KNN imputation, then trains five scikit-learn classifiers (best: Random Forest, test F1 ~0.97). Artifacts and final_model sync to S3; FastAPI exposes /train and /predict (CSV upload → HTML results). Docker entrypoint pulls the latest model from S3; GitHub Actions builds to ECR and deploys on a self-hosted EC2 runner. Dataset: 11,055 records, 30 features.",
  technologies: ["Python", "scikit-learn", "MongoDB Atlas", "MLflow", "FastAPI", "Amazon S3", "Docker", "Amazon ECR", "AWS EC2", "GitHub Actions", "CI/CD"],
  images: ["/projects/network-system-mlops.png"],
  repo: "https://github.com/SafwenCherif/networking-security-mlops",
},

];
